---
kind: List
apiVersion: v1
metadata: {}
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: caas-ui
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: caas-ui
    name: caas-ui
    namespace: caas-ui
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: caas-ui
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: caas-ui
      spec:
        containers:
        - image: quay.io/__USER__/caas-ui:latest
          imagePullPolicy: Always
          name: caas-ui
          ports:
          - containerPort: 9443
            protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          volumeMounts:
          - mountPath: "/var/serving-cert"
            name: plugin-serving-cert
            readOnly: true
          - mountPath: "/etc/nginx/nginx.conf"
            name: nginx-conf
            readOnly: true
            subPath: nginx.conf
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumes:
        - name: plugin-serving-cert
          secret:
            defaultMode: 420
            secretName: plugin-serving-cert
        - configMap:
            defaultMode: 420
            name: nginx-conf
          name: nginx-conf
- apiVersion: v1
  data:
    nginx.conf: |
      error_log /dev/stdout info;
      events {}
      http {
        access_log         /dev/stdout;
        include            /etc/nginx/mime.types;
        default_type       application/octet-stream;
        keepalive_timeout  65;
        server {
          listen       9443 ssl;
          ssl_certificate /var/serving-cert/tls.crt;
          ssl_certificate_key /var/serving-cert/tls.key;
          ssl_protocols TLSv1.2 TLSv1.3;
          location / {
              root   /usr/share/nginx/html;
          }
          error_page   500 502 503 504  /50x.html;
          location = /50x.html {
              root   /usr/share/nginx/html;
          }
          location = /plugin-entry.js {
              root   /usr/share/nginx/html;
              expires -1;
              add_header 'Cache-Control' 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
          }
          location = /plugin-manifest.json {
              root   /usr/share/nginx/html;
              expires -1;
              add_header 'Cache-Control' 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
          }
        }
      }
  kind: ConfigMap
  metadata:
    labels:
      app: caas-ui
      app.kubernetes.io/part-of: caas-ui
    name: nginx-conf
    namespace: caas-ui
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: plugin-serving-cert
    labels:
      app: caas-ui
      app.kubernetes.io/component: caas-ui
      app.kubernetes.io/instance: caas-ui
      app.kubernetes.io/part-of: caas-ui
    name: caas-ui
    namespace: caas-ui
  spec:
    ports:
    - name: 9443-tcp
      port: 9443
      protocol: TCP
      targetPort: 9443
    selector:
      app: caas-ui
    sessionAffinity: None
    type: ClusterIP
- apiVersion: console.openshift.io/v1alpha1
  kind: ConsolePlugin
  metadata:
    name: clustertemplates-plugin
  spec:
    displayName: Console Plugin Template
    service:
      basePath: "/"
      name: caas-ui
      namespace: caas-ui
      port: 9443

